//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection_Entry
    {
        public long Collection_Entry_ID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> LeadID { get; set; }
        public Nullable<int> PaymentModeID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
        public bool TDSapplicable { get; set; }
        public Nullable<decimal> TDSAmount { get; set; }
        public Nullable<decimal> BadDebtsAmount { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string ChequeName { get; set; }
        public Nullable<int> BankID { get; set; }
        public string DraweeName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<bool> isAdvanceEntry { get; set; }
        public Nullable<decimal> TotalAmountToUseOnlyForCustomer { get; set; }
        public Nullable<decimal> BalanceUseOnlyForCustomer { get; set; }
        public Nullable<bool> isPartPayment { get; set; }
        public Nullable<long> original_collection_entry_id_for_part_payment { get; set; }
    
        public virtual Bank_Master Bank_Master { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        public virtual Lead Lead { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
    }
}
