//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consult_Person_Import_Format
    {
        public long Consult_Person_Import_Format_ID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Contact_Number_1 { get; set; }
        public string Contact_Number_2 { get; set; }
        public string Contact_Number_3 { get; set; }
        public string Contact_Number_4 { get; set; }
        public string Contact_Number_5 { get; set; }
        public string Email_1 { get; set; }
        public string Email_2 { get; set; }
        public string Email_3 { get; set; }
        public string Email_4 { get; set; }
        public string Email_5 { get; set; }
        public string Errors { get; set; }
        public string FileName { get; set; }
    }
}
