//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.Contract_Customer_Service_Address_Mapping = new HashSet<Contract_Customer_Service_Address_Mapping>();
            this.Contract_Customer_Service_Mapping = new HashSet<Contract_Customer_Service_Mapping>();
            this.Contract_Services_Mapping = new HashSet<Contract_Services_Mapping>();
            this.Contracts_Service_Address_Mapping = new HashSet<Contracts_Service_Address_Mapping>();
            this.Invoices = new HashSet<Invoice>();
            this.Lead_Services_Mapping = new HashSet<Lead_Services_Mapping>();
            this.Servicings = new HashSet<Servicing>();
        }
    
        public int ContractID { get; set; }
        public string ContractNo { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string TypeOfContract { get; set; }
        public string PurchaseOrderNo { get; set; }
        public Nullable<System.DateTime> PurchaseOtrderDate { get; set; }
        public long CustomerID { get; set; }
        public bool SiteAddressSameAsBillingAddress { get; set; }
        public string Remark { get; set; }
        public int BalanceAmount { get; set; }
        public int BranchID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> Contract_From_Date { get; set; }
        public Nullable<System.DateTime> Contract_To_Date { get; set; }
        public Nullable<decimal> FinalContractRate { get; set; }
        public string PaidByCustomer { get; set; }
        public string ExecutiveName { get; set; }
        public string ExecutveContactNo { get; set; }
        public Nullable<int> PaymentModeID { get; set; }
        public Nullable<int> PaymentTermID { get; set; }
        public Nullable<int> PeriodsOfContractID { get; set; }
        public string BookBy { get; set; }
        public string BookByContactNo { get; set; }
        public bool SendWelcomeMessage { get; set; }
        public Nullable<int> PremisesTypeID { get; set; }
        public Nullable<int> Premises_Area_ID { get; set; }
        public string AppSqFtArea { get; set; }
        public Nullable<int> ExecutiveID { get; set; }
        public Nullable<int> BookByID { get; set; }
        public Nullable<int> LeadID { get; set; }
        public Nullable<int> ExistingContractsID { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Customer_Service_Address_Mapping> Contract_Customer_Service_Address_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Customer_Service_Mapping> Contract_Customer_Service_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Services_Mapping> Contract_Services_Mapping { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts_Service_Address_Mapping> Contracts_Service_Address_Mapping { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual UserLogin UserLogin2 { get; set; }
        public virtual Lead Lead { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual PaymentTerm PaymentTerm { get; set; }
        public virtual PeriodsOfContract PeriodsOfContract { get; set; }
        public virtual PeriodsOfContract PeriodsOfContract1 { get; set; }
        public virtual PeriodsOfContract PeriodsOfContract2 { get; set; }
        public virtual PremisesType PremisesType { get; set; }
        public virtual Premises_Area_Master Premises_Area_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lead_Services_Mapping> Lead_Services_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicing> Servicings { get; set; }
    }
}
