//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_Customer_Service_Mapping
    {
        public long Contract_Customer_Service_Mapping_ID { get; set; }
        public int ContractID { get; set; }
        public int Customer_Services_Mapping_ID { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Customer_Services_Mapping Customer_Services_Mapping { get; set; }
    }
}
