//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts_Service_Address_Mapping
    {
        public long Contracts_Service_Address_Mapping_ID { get; set; }
        public long CustomerID { get; set; }
        public long Customers_Service_Address_Mapping_ID { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int ContractID { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Customers_Service_Address_Mapping Customers_Service_Address_Mapping { get; set; }
    }
}
