//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers_Billing_Address_Mapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers_Billing_Address_Mapping()
        {
            this.Customers_Billing_Address_Cell_No_Mapping = new HashSet<Customers_Billing_Address_Cell_No_Mapping>();
            this.Customers_Billing_Address_Email_Mapping = new HashSet<Customers_Billing_Address_Email_Mapping>();
            this.Customers_Billing_Address_Tel_No_Mapping = new HashSet<Customers_Billing_Address_Tel_No_Mapping>();
        }
    
        public long Customers_Billing_Address_Mapping_ID { get; set; }
        public long CustomerID { get; set; }
        public int BillingLocationID { get; set; }
        public int BillingCityID { get; set; }
        public string BillingPincode { get; set; }
        public int BillingStateID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string GSTNo { get; set; }
    
        public virtual City City { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Billing_Address_Cell_No_Mapping> Customers_Billing_Address_Cell_No_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Billing_Address_Email_Mapping> Customers_Billing_Address_Email_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Billing_Address_Tel_No_Mapping> Customers_Billing_Address_Tel_No_Mapping { get; set; }
        public virtual Location Location { get; set; }
        public virtual State State { get; set; }
    }
}
