//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Services_Mapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_Services_Mapping()
        {
            this.Contract_Customer_Service_Mapping = new HashSet<Contract_Customer_Service_Mapping>();
        }
    
        public int Customer_Services_Mapping_ID { get; set; }
        public long CustomerID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public int ServiceGroupID { get; set; }
        public int FrequencyOfServiceID { get; set; }
        public int Rate { get; set; }
        public Nullable<bool> GST { get; set; }
        public Nullable<short> Qty { get; set; }
        public Nullable<int> Tax { get; set; }
        public Nullable<int> FinalRatePerService { get; set; }
        public string ShortServiceScope { get; set; }
        public Nullable<int> PeriodsOfContractID { get; set; }
        public Nullable<System.DateTime> ServiceStartDate { get; set; }
        public Nullable<System.DateTime> POCStartDate { get; set; }
        public Nullable<System.DateTime> POCEndDate { get; set; }
        public Nullable<int> FrequencyOfInvoiceID { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<int> Short_Service_Scope_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Customer_Service_Mapping> Contract_Customer_Service_Mapping { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual FrequencyOfInvoice FrequencyOfInvoice { get; set; }
        public virtual FrequencyOfService FrequencyOfService { get; set; }
        public virtual PeriodsOfContract PeriodsOfContract { get; set; }
        public virtual Service Service { get; set; }
        public virtual ServiceGroup ServiceGroup { get; set; }
        public virtual Short_Service_Scope_Master Short_Service_Scope_Master { get; set; }
    }
}
