//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Collection_Entry = new HashSet<Collection_Entry>();
            this.Contracts = new HashSet<Contract>();
            this.Contracts_Service_Address_Mapping = new HashSet<Contracts_Service_Address_Mapping>();
            this.Customer_Services_Mapping = new HashSet<Customer_Services_Mapping>();
            this.Customers_Consult_Person_Mapping = new HashSet<Customers_Consult_Person_Mapping>();
            this.Customers_Billing_Address_Mapping = new HashSet<Customers_Billing_Address_Mapping>();
            this.Customers_Service_Address_Mapping = new HashSet<Customers_Service_Address_Mapping>();
            this.Estimates = new HashSet<Estimate>();
            this.Invoice_Customer_Service_Address_Mapping = new HashSet<Invoice_Customer_Service_Address_Mapping>();
            this.Invoice_Services_Mapping = new HashSet<Invoice_Services_Mapping>();
            this.Invoices = new HashSet<Invoice>();
            this.Servicings = new HashSet<Servicing>();
        }
    
        public long CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerType { get; set; }
        public string StatusReason { get; set; }
        public string TelNumber { get; set; }
        public string CellNumber { get; set; }
        public string EmailId { get; set; }
        public string GstinNo { get; set; }
        public string Remarks { get; set; }
        public int BranchID { get; set; }
        public int SourceID { get; set; }
        public int SubSourceID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastupdatedOn { get; set; }
        public Nullable<int> LastupdatedBy { get; set; }
        public long CustomerStatusID { get; set; }
        public string ConsultPerson { get; set; }
        public string ConsultPersonDesignation { get; set; }
        public bool IsBillAddSame { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string FacebookLink { get; set; }
        public string TwitterLink { get; set; }
        public string LinkedInLink { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<byte> GST_Type_Enum { get; set; }
        public Nullable<System.DateTime> CustomerDate { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public Nullable<int> IndustryID { get; set; }
        public Nullable<int> LeadID { get; set; }
        public string CustomerNo { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collection_Entry> Collection_Entry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts_Service_Address_Mapping> Contracts_Service_Address_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Services_Mapping> Customer_Services_Mapping { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual CustomerStatu CustomerStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Consult_Person_Mapping> Customers_Consult_Person_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Billing_Address_Mapping> Customers_Billing_Address_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Service_Address_Mapping> Customers_Service_Address_Mapping { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual Source Source { get; set; }
        public virtual Source Source1 { get; set; }
        public virtual Lead Lead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estimate> Estimates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Customer_Service_Address_Mapping> Invoice_Customer_Service_Address_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Services_Mapping> Invoice_Services_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicing> Servicings { get; set; }
    }
}
