//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers_Consult_Person_Mapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers_Consult_Person_Mapping()
        {
            this.Customers_Consult_Person_Cell_No_Mapping = new HashSet<Customers_Consult_Person_Cell_No_Mapping>();
            this.Customers_Consult_Person_Email_Mapping = new HashSet<Customers_Consult_Person_Email_Mapping>();
            this.Customers_Consult_Person_Tel_No_Mapping = new HashSet<Customers_Consult_Person_Tel_No_Mapping>();
        }
    
        public long Customers_Consult_Person_Mapping_ID { get; set; }
        public long CustomerID { get; set; }
        public string Consult_Person_Name { get; set; }
        public string Consult_Person_Designation { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastupdatedOn { get; set; }
        public Nullable<int> LastupdatedBy { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Consult_Person_Cell_No_Mapping> Customers_Consult_Person_Cell_No_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Consult_Person_Email_Mapping> Customers_Consult_Person_Email_Mapping { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Consult_Person_Tel_No_Mapping> Customers_Consult_Person_Tel_No_Mapping { get; set; }
    }
}
