//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers_Service_Address_Mapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers_Service_Address_Mapping()
        {
            this.Contract_Customer_Service_Address_Mapping = new HashSet<Contract_Customer_Service_Address_Mapping>();
            this.Contract_Customer_Service_Address_Mapping1 = new HashSet<Contract_Customer_Service_Address_Mapping>();
            this.Contracts_Service_Address_Mapping = new HashSet<Contracts_Service_Address_Mapping>();
            this.Customers_Service_Address_Cell_No_Mapping = new HashSet<Customers_Service_Address_Cell_No_Mapping>();
            this.Customers_Service_Address_Email_Mapping = new HashSet<Customers_Service_Address_Email_Mapping>();
            this.Customers_Service_Address_Tel_No_Mapping = new HashSet<Customers_Service_Address_Tel_No_Mapping>();
        }
    
        public long Customers_Service_Address_Mapping_ID { get; set; }
        public long CustomerID { get; set; }
        public int ServiceLocationID { get; set; }
        public int ServiceCityID { get; set; }
        public string ServicePincode { get; set; }
        public int ServiceStateID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string ServiceAddressConsultPerson { get; set; }
        public string ServiceAddressTelNosCSV { get; set; }
        public string ServiceAddressCellNosCSV { get; set; }
        public string ServiceAddressEmailsCSV { get; set; }
        public string Customer_Service_Address_Tel_No_1 { get; set; }
        public string Customer_Service_Address_Tel_No_2 { get; set; }
        public string Customer_Service_Address_Tel_No_3 { get; set; }
        public string Customer_Service_Address_Tel_No_4 { get; set; }
        public string Customer_Service_Address_Tel_No_5 { get; set; }
        public string Customer_Service_Address_Cell_No_1 { get; set; }
        public string Customer_Service_Address_Cell_No_2 { get; set; }
        public string Customer_Service_Address_Cell_No_3 { get; set; }
        public string Customer_Service_Address_Cell_No_4 { get; set; }
        public string Customer_Service_Address_Cell_No_5 { get; set; }
        public string Customer_Service_Address_Email_1 { get; set; }
        public string Customer_Service_Address_Email_2 { get; set; }
        public string Customer_Service_Address_Email_3 { get; set; }
        public string Customer_Service_Address_Email_4 { get; set; }
        public string Customer_Service_Address_Email_5 { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Customer_Service_Address_Mapping> Contract_Customer_Service_Address_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Customer_Service_Address_Mapping> Contract_Customer_Service_Address_Mapping1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts_Service_Address_Mapping> Contracts_Service_Address_Mapping { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Service_Address_Cell_No_Mapping> Customers_Service_Address_Cell_No_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Service_Address_Email_Mapping> Customers_Service_Address_Email_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Service_Address_Tel_No_Mapping> Customers_Service_Address_Tel_No_Mapping { get; set; }
        public virtual Location Location { get; set; }
        public virtual State State { get; set; }
    }
}
