//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents_Templates
    {
        public int Document_Template_ID { get; set; }
        public string Document_Name { get; set; }
        public string Document_Header { get; set; }
        public string Document_Footer { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int CreatedByUserID { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> LastUpdatedByUserID { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
    }
}
