//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Contracts = new HashSet<Contract>();
            this.Employees1 = new HashSet<Employee>();
            this.Leads_Follow_Up_Details = new HashSet<Leads_Follow_Up_Details>();
            this.Leads_Follow_Up_Details1 = new HashSet<Leads_Follow_Up_Details>();
            this.Servicing_Technician_Mapping = new HashSet<Servicing_Technician_Mapping>();
            this.UserLogins = new HashSet<UserLogin>();
            this.Leads = new HashSet<Lead>();
            this.Leads_History = new HashSet<Leads_History>();
        }
    
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<System.DateTime> EnrolmentDate { get; set; }
        public string EmployeePhotoPath { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CellNos { get; set; }
        public string EmailID { get; set; }
        public string EmployeeStatus { get; set; }
        public string Remarks { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<int> UpdatedByUserID { get; set; }
        public string LoginID { get; set; }
        public string Password { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<int> EmployeeStatusID { get; set; }
        public string CurrentAddressAddressLine1 { get; set; }
        public string CurrentAddressAddressLine2 { get; set; }
        public string CurrentAddressAddressLine3 { get; set; }
        public Nullable<int> CurrentAddressLocationID { get; set; }
        public Nullable<int> CurrentAddressCityID { get; set; }
        public string CurrentAddressPincode { get; set; }
        public Nullable<int> CurrentAddressStateID { get; set; }
        public string PermAddressAddressLine1 { get; set; }
        public string PermAddressAddressLine2 { get; set; }
        public string PermAddressAddressLine3 { get; set; }
        public Nullable<int> PermAddressLocationID { get; set; }
        public Nullable<int> PermAddressCityID { get; set; }
        public string PermAddressPincode { get; set; }
        public Nullable<int> PermAddressStateID { get; set; }
        public Nullable<byte> Gender_Enum { get; set; }
        public Nullable<byte> Marital_Status_Enum { get; set; }
        public Nullable<byte> Blood_Group_Enum { get; set; }
        public string Qualification { get; set; }
        public string PrimaryCellNumber { get; set; }
        public string SecondaryCellNumber { get; set; }
        public string PersonalEmailID { get; set; }
        public string CompanyEmailID { get; set; }
        public string BasicSalary { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<System.DateTime> DateOfProbation { get; set; }
        public Nullable<System.DateTime> DateOfJConfirmation { get; set; }
        public Nullable<System.DateTime> DateOfLeaving { get; set; }
        public Nullable<int> Report_To { get; set; }
        public string Pan_Number { get; set; }
        public string AADHAR_Number { get; set; }
        public string ESIC_Number { get; set; }
        public string Other { get; set; }
        public string Work_Experience { get; set; }
        public Nullable<int> BankID { get; set; }
        public string Accounty_Holder_Name { get; set; }
        public string Account_Number { get; set; }
        public string IFSC_Code { get; set; }
        public string Bank_Branch { get; set; }
        public string Employee_Photo { get; set; }
        public Nullable<bool> isCurrentAddressSameasPermanentAddress { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string PFNumber { get; set; }
        public string POrtfolio { get; set; }
    
        public virtual Bank_Master Bank_Master { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual Department_Master Department_Master { get; set; }
        public virtual EmployeeDesignation EmployeeDesignation { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual Employees_Status_Master Employees_Status_Master { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual State State1 { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leads_Follow_Up_Details> Leads_Follow_Up_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leads_Follow_Up_Details> Leads_Follow_Up_Details1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicing_Technician_Mapping> Servicing_Technician_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLogin> UserLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lead> Leads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leads_History> Leads_History { get; set; }
    }
}
