//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estimate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estimate()
        {
            this.Estimate_Services_Mapping = new HashSet<Estimate_Services_Mapping>();
        }
    
        public int EstimateID { get; set; }
        public bool NewCustomer { get; set; }
        public bool ExistingCustomer { get; set; }
        public Nullable<int> LeadID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public System.DateTime GSTinDate { get; set; }
        public string FinalEstimateRate { get; set; }
        public string KindAttention { get; set; }
        public string Subject { get; set; }
        public string WelcomeSentence { get; set; }
        public string Footer { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public string RATE { get; set; }
        public string TAX { get; set; }
        public string FinalRate { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> EstimateDate { get; set; }
        public string ServiceScope { get; set; }
        public bool isNewEstimate { get; set; }
        public Nullable<int> OriginalEstimateID { get; set; }
        public int RevisionNo { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estimate_Services_Mapping> Estimate_Services_Mapping { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        public virtual Lead Lead { get; set; }
    }
}
