//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estimates_History
    {
        public long Estimates_History_ID { get; set; }
        public Nullable<int> EstimateID { get; set; }
        public bool NewCustomer { get; set; }
        public bool ExistingCustomer { get; set; }
        public Nullable<int> LeadID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public System.DateTime GSTinDate { get; set; }
        public string FinalEstimateRate { get; set; }
        public string KindAttention { get; set; }
        public string Subject { get; set; }
        public string WelcomeSentence { get; set; }
        public string Footer { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public string RATE { get; set; }
        public string TAX { get; set; }
        public string FinalRate { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> EstimateDate { get; set; }
        public string ServiceScope { get; set; }
        public bool isNewEstimate { get; set; }
        public Nullable<int> OriginalEstimateID { get; set; }
        public int RevisionNo { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public System.DateTime History_Created_On { get; set; }
    }
}
