//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrequencyOfService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FrequencyOfService()
        {
            this.Contract_Services_Mapping = new HashSet<Contract_Services_Mapping>();
            this.Customer_Services_Mapping = new HashSet<Customer_Services_Mapping>();
            this.Estimate_Services_Mapping = new HashSet<Estimate_Services_Mapping>();
            this.Invoice_Services_Mapping = new HashSet<Invoice_Services_Mapping>();
            this.Lead_Services_Mapping_History = new HashSet<Lead_Services_Mapping_History>();
            this.Lead_Services_Mapping = new HashSet<Lead_Services_Mapping>();
            this.Servicings = new HashSet<Servicing>();
        }
    
        public int FrequencyOfServiceID { get; set; }
        public string FrequencyOfService1 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<int> Order { get; set; }
        public int Duration_Between_2_Services_Year { get; set; }
        public int Duration_Between_2_Services_Month { get; set; }
        public int Duration_Between_2_Services_Day { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Services_Mapping> Contract_Services_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Services_Mapping> Customer_Services_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estimate_Services_Mapping> Estimate_Services_Mapping { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Services_Mapping> Invoice_Services_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lead_Services_Mapping_History> Lead_Services_Mapping_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lead_Services_Mapping> Lead_Services_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicing> Servicings { get; set; }
    }
}
