//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Collection_Entry = new HashSet<Collection_Entry>();
            this.Invoice_Customer_Service_Address_Mapping = new HashSet<Invoice_Customer_Service_Address_Mapping>();
            this.Invoice_Services_Mapping = new HashSet<Invoice_Services_Mapping>();
        }
    
        public int InvoiceID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public bool SendDetailsMessage { get; set; }
        public long CustomerID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public string PurchaseOrderNo { get; set; }
        public Nullable<System.DateTime> PurchaseOrderDate { get; set; }
        public string ExecutiveName { get; set; }
        public Nullable<int> TypeOfPremisesID { get; set; }
        public Nullable<short> NoOfWings { get; set; }
        public Nullable<short> NoOfFloors { get; set; }
        public Nullable<System.DateTime> Period_Of_Contract_Start_Date { get; set; }
        public Nullable<System.DateTime> Period_Of_Contract_End_Date { get; set; }
        public Nullable<System.DateTime> Period_Of_Invoice_Start_Date { get; set; }
        public Nullable<System.DateTime> Period_Of_Invoice_End_Date { get; set; }
        public string PremisesArea { get; set; }
        public string PremisesAppSqFtArea { get; set; }
        public Nullable<int> PaymentModeID { get; set; }
        public Nullable<int> PaymentTermID { get; set; }
        public Nullable<decimal> FinalInvoiceRate { get; set; }
        public string PaidByCustomer { get; set; }
        public string BalanceAmount { get; set; }
        public string ExecutveContactNo { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public byte Tax_Invoice_Type_Enum { get; set; }
        public Nullable<byte> GST_Type_Enum { get; set; }
        public Nullable<short> NoOfFlats { get; set; }
        public string BadDebtsAmount { get; set; }
        public Nullable<decimal> SGSTSumOfAllServices { get; set; }
        public Nullable<decimal> CGSTSumOfAllServices { get; set; }
        public Nullable<decimal> IGSTSumOfAllServices { get; set; }
        public Nullable<decimal> AlreadyPaidSum { get; set; }
        public Nullable<int> PremisesTypeID { get; set; }
        public Nullable<int> Premises_Area_ID { get; set; }
        public string AppSqFtArea { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collection_Entry> Collection_Entry { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Customer_Service_Address_Mapping> Invoice_Customer_Service_Address_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Services_Mapping> Invoice_Services_Mapping { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual PaymentTerm PaymentTerm { get; set; }
        public virtual PremisesType PremisesType { get; set; }
        public virtual Premises_Area_Master Premises_Area_Master { get; set; }
    }
}
