//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Services_Mapping
    {
        public int Invoice_Services_Mapping_ID { get; set; }
        public int InvoiceID { get; set; }
        public long CustomerID { get; set; }
        public int ServiceGroupID { get; set; }
        public int ServiceID { get; set; }
        public string ShortServiceScope { get; set; }
        public int FrequencyOfServiceID { get; set; }
        public string SACCode { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<short> Qty { get; set; }
        public Nullable<bool> GST { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<int> FinalRatePerService { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<int> PremisesTypeID { get; set; }
        public Nullable<int> Premises_Area_ID { get; set; }
        public string AppSqFtArea { get; set; }
        public Nullable<int> Short_Service_Scope_ID { get; set; }
        public Nullable<int> PeriodsOfContractID { get; set; }
        public Nullable<System.DateTime> ServiceStartDate { get; set; }
        public Nullable<System.DateTime> POCStartDate { get; set; }
        public Nullable<System.DateTime> POCEndDate { get; set; }
        public Nullable<System.DateTime> POIStartDate { get; set; }
        public Nullable<System.DateTime> POIEndDate { get; set; }
        public Nullable<int> FrequencyOfInvoiceID { get; set; }
        public string ServiceStartDateInString { get; set; }
        public string POCStartDateInString { get; set; }
        public string POCEndDateInString { get; set; }
        public string POIStartDateInString { get; set; }
        public string POIEndDateInString { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual FrequencyOfInvoice FrequencyOfInvoice { get; set; }
        public virtual FrequencyOfService FrequencyOfService { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual PeriodsOfContract PeriodsOfContract { get; set; }
        public virtual PremisesType PremisesType { get; set; }
        public virtual Premises_Area_Master Premises_Area_Master { get; set; }
        public virtual ServiceGroup ServiceGroup { get; set; }
        public virtual Service Service { get; set; }
        public virtual Short_Service_Scope_Master Short_Service_Scope_Master { get; set; }
    }
}
