//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leads_History
    {
        public long Leads_History_ID { get; set; }
        public int LeadID { get; set; }
        public Nullable<System.DateTime> LeadDate { get; set; }
        public string Title { get; set; }
        public string CustomerName { get; set; }
        public string TelNo { get; set; }
        public string CellNo { get; set; }
        public string Pincode { get; set; }
        public Nullable<int> CityID { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> SubSourceID { get; set; }
        public Nullable<int> TypeOfPremisesID { get; set; }
        public Nullable<int> TeleCallerID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> VisitAllocate { get; set; }
        public Nullable<System.DateTime> VisitDateTime { get; set; }
        public string VisitReport { get; set; }
        public string RATE { get; set; }
        public string TAX { get; set; }
        public string FinalRate { get; set; }
        public string CustomerPriority { get; set; }
        public Nullable<System.DateTime> NextFollowUpDateTime { get; set; }
        public string SpecialInstructions { get; set; }
        public string FollowUpDetails { get; set; }
        public Nullable<int> LeadStatusID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<short> NoOfWings { get; set; }
        public Nullable<short> NoOfFloors { get; set; }
        public Nullable<System.DateTime> LeasdClosedDateTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public string ConsultPerson { get; set; }
        public string ConsultPersonDesignation { get; set; }
        public Nullable<int> IndustryID { get; set; }
        public string PremisesArea { get; set; }
        public string PremisesAppSqFtArea { get; set; }
        public string StatusReason { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> Premises_Area_ID { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public Nullable<System.TimeSpan> ServiceTime { get; set; }
        public Nullable<System.TimeSpan> VisitTime { get; set; }
        public Nullable<System.TimeSpan> NextFollowUpTime { get; set; }
        public Nullable<short> NoOfFlats { get; set; }
        public System.DateTime History_Created_On { get; set; }
        public string LeadNumber { get; set; }
        public string OtherDetails { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual City City { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual LeadStatus LeadStatus { get; set; }
        public virtual Location Location { get; set; }
        public virtual Premises_Area_Master Premises_Area_Master { get; set; }
        public virtual Source Source { get; set; }
        public virtual State State { get; set; }
        public virtual Source Source1 { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        public virtual PremisesType PremisesType { get; set; }
        public virtual UserLogin UserLogin2 { get; set; }
    }
}
