//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leads_Import_Format
    {
        public long Leads_Import_Format_ID { get; set; }
        public string Title { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Customer_Name { get; set; }
        public string Date { get; set; }
        public string ConsultPerson { get; set; }
        public string Designation { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public string Address_Line_3 { get; set; }
        public string Location { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string State { get; set; }
        public string Tel_No_1 { get; set; }
        public string Tel_No_2 { get; set; }
        public string Tel_No_3 { get; set; }
        public string Tel_No_4 { get; set; }
        public string Tel_No_5 { get; set; }
        public string Cell_No_1 { get; set; }
        public string Cell_No_2 { get; set; }
        public string Cell_No_3 { get; set; }
        public string Cell_No_4 { get; set; }
        public string Cell_No_5 { get; set; }
        public string Email_1 { get; set; }
        public string Email_2 { get; set; }
        public string Email_3 { get; set; }
        public string Email_4 { get; set; }
        public string Email_5 { get; set; }
        public string Type_Of_Premise { get; set; }
        public string No_Of_Wings { get; set; }
        public string No_Of_Floors { get; set; }
        public string No_Of_Flats { get; set; }
        public string Premises_Area { get; set; }
        public string Approx_Sq_Ft_Area { get; set; }
        public string Other_Details { get; set; }
        public string Industry { get; set; }
        public string Visit_Allocate { get; set; }
        public string Visit_Date { get; set; }
        public string Visit_Time { get; set; }
        public string Service_Date { get; set; }
        public string Service_Time { get; set; }
        public string Visit_Report { get; set; }
        public string Special_Instructions { get; set; }
        public string Source { get; set; }
        public string Sub_Source { get; set; }
        public string Follow_Up_Details { get; set; }
        public string Next_Follow_Up_Date { get; set; }
        public string Next_Follow_Up_Time { get; set; }
        public string Customer_Priority { get; set; }
        public string Lead_Status { get; set; }
        public string Status_Reason { get; set; }
        public string Branch { get; set; }
        public string Tele_Caller { get; set; }
        public string Errors { get; set; }
        public string FileName { get; set; }
        public string Consult_Person_1_Name { get; set; }
        public string Consult_Person_1_Designation { get; set; }
        public string Consult_Person_1_Contact_Number_1 { get; set; }
        public string Consult_Person_1_Contact_Number_2 { get; set; }
        public string Consult_Person_1_Contact_Number_3 { get; set; }
        public string Consult_Person_1_Contact_Number_4 { get; set; }
        public string Consult_Person_1_Contact_Number_5 { get; set; }
        public string Consult_Person_1_Email_1 { get; set; }
        public string Consult_Person_1_Email_2 { get; set; }
        public string Consult_Person_1_Email_3 { get; set; }
        public string Consult_Person_1_Email_4 { get; set; }
        public string Consult_Person_1_Email_5 { get; set; }
        public string Consult_Person_2_Name { get; set; }
        public string Consult_Person_2_Designation { get; set; }
        public string Consult_Person_2_Contact_Number_1 { get; set; }
        public string Consult_Person_2_Contact_Number_2 { get; set; }
        public string Consult_Person_2_Contact_Number_3 { get; set; }
        public string Consult_Person_2_Contact_Number_4 { get; set; }
        public string Consult_Person_2_Contact_Number_5 { get; set; }
        public string Consult_Person_2_Email_1 { get; set; }
        public string Consult_Person_2_Email_2 { get; set; }
        public string Consult_Person_2_Email_3 { get; set; }
        public string Consult_Person_2_Email_4 { get; set; }
        public string Consult_Person_2_Email_5 { get; set; }
        public string Service_Group_1 { get; set; }
        public string Service_1 { get; set; }
        public string Frequency_Of_Service_1 { get; set; }
        public string Qty_1 { get; set; }
        public string Rate_1 { get; set; }
        public string GST_1 { get; set; }
        public string Service_Group_2 { get; set; }
        public string Service_2 { get; set; }
        public string Frequency_Of_Service_2 { get; set; }
        public string Qty_2 { get; set; }
        public string GST_2 { get; set; }
        public string Service_Group_3 { get; set; }
        public string Service_3 { get; set; }
        public string Frequency_Of_Service_3 { get; set; }
        public string Qty_3 { get; set; }
        public string Rate_3 { get; set; }
        public string GST_3 { get; set; }
        public string Rate_2 { get; set; }
    }
}
