//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead_Services_Mapping_History
    {
        public long Lead_Services_Mapping_History_ID { get; set; }
        public int Lead_Services_Mapping_ID { get; set; }
        public int LeadID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public int ServiceGroupID { get; set; }
        public Nullable<int> FrequencyOfServiceID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<bool> GST { get; set; }
        public Nullable<short> Qty { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> FinalRatePerService { get; set; }
        public Nullable<int> PeriodsOfContractID { get; set; }
        public Nullable<System.DateTime> ServiceStartDate { get; set; }
        public Nullable<System.DateTime> POCStartDate { get; set; }
        public Nullable<System.DateTime> POCEndDate { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public System.DateTime History_Created_On { get; set; }
    
        public virtual FrequencyOfService FrequencyOfService { get; set; }
        public virtual Lead_Services_Mapping Lead_Services_Mapping { get; set; }
        public virtual Lead Lead { get; set; }
        public virtual PeriodsOfContract PeriodsOfContract { get; set; }
        public virtual Service Service { get; set; }
        public virtual ServiceGroup ServiceGroup { get; set; }
    }
}
