//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead_Consult_Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lead_Consult_Person()
        {
            this.Lead_Consult_Person_Contact_No_Mapping = new HashSet<Lead_Consult_Person_Contact_No_Mapping>();
            this.Lead_Consult_Person_Email_Mapping = new HashSet<Lead_Consult_Person_Email_Mapping>();
        }
    
        public int Lead_Consult_Person_ID { get; set; }
        public int LeadID { get; set; }
        public string PersonaName { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lead_Consult_Person_Contact_No_Mapping> Lead_Consult_Person_Contact_No_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lead_Consult_Person_Email_Mapping> Lead_Consult_Person_Email_Mapping { get; set; }
        public virtual Lead Lead { get; set; }
    }
}
