//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead_Consult_Person_Contact_No_Mapping
    {
        public int Lead_Consult_Person_Contact_No_Mapping_ID { get; set; }
        public int Lead_Consult_Person_ID { get; set; }
        public string Lead_Consult_Person_Contact_No { get; set; }
    
        public virtual Lead_Consult_Person Lead_Consult_Person { get; set; }
    }
}
