//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pending_Leads
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pending_Leads()
        {
            this.Pending_Leads_Services = new HashSet<Pending_Leads_Services>();
        }
    
        public int PendingLeadID { get; set; }
        public string Name { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string Enquiry { get; set; }
        public string Location { get; set; }
        public string City { get; set; }
        public string FinalRate { get; set; }
        public string AdditionalComment { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string MobileNumber { get; set; }
        public string Pincode { get; set; }
        public Nullable<System.DateTime> SelectedDateTime { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string FromForm { get; set; }
        public Nullable<int> LeadID { get; set; }
    
        public virtual Lead Lead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pending_Leads_Services> Pending_Leads_Services { get; set; }
    }
}
