//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Master
    {
        public int Product_ID { get; set; }
        public int Product_Category_ID { get; set; }
        public string Product { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> LastUpdatedByUserID { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> Product_SubCategory_ID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string UOM { get; set; }
        public string Description { get; set; }
        public Nullable<bool> TaxApplicable { get; set; }
        public Nullable<decimal> TaxInPercentage { get; set; }
    
        public virtual Product_Category_Master Product_Category_Master { get; set; }
        public virtual Product_Category_Master Product_Category_Master1 { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
