//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SadguruCRMEntities : DbContext
    {
        public SadguruCRMEntities()
            : base("metadata=res://*/Models.SadguruCRMModel.csdl|res://*/Models.SadguruCRMModel.ssdl|res://*/Models.SadguruCRMModel.msl;provider=System.Data.SqlClient;provider connection string='data source=az1-wsq1.my-hosting-panel.com;initial catalog=thibowco_sadgurucrm;persist security info=True;user id=thibowco_sadgurucrm;password=Borivali2345;MultipleActiveResultSets=True;App=EntityFramework'")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank_Master> Bank_Master { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Chemicals_Master> Chemicals_Master { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Collection_Entry> Collection_Entry { get; set; }
        public virtual DbSet<Consult_Person_Import_Format> Consult_Person_Import_Format { get; set; }
        public virtual DbSet<Contract_Customer_Service_Address_Mapping> Contract_Customer_Service_Address_Mapping { get; set; }
        public virtual DbSet<Contract_Customer_Service_Mapping> Contract_Customer_Service_Mapping { get; set; }
        public virtual DbSet<Contract_Services_Mapping> Contract_Services_Mapping { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Contracts_Service_Address_Mapping> Contracts_Service_Address_Mapping { get; set; }
        public virtual DbSet<Customer_Services_Mapping> Customer_Services_Mapping { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customers_Billing_Address_Cell_No_Mapping> Customers_Billing_Address_Cell_No_Mapping { get; set; }
        public virtual DbSet<Customers_Billing_Address_Email_Mapping> Customers_Billing_Address_Email_Mapping { get; set; }
        public virtual DbSet<Customers_Billing_Address_Mapping> Customers_Billing_Address_Mapping { get; set; }
        public virtual DbSet<Customers_Billing_Address_Tel_No_Mapping> Customers_Billing_Address_Tel_No_Mapping { get; set; }
        public virtual DbSet<Customers_Consult_Person_Cell_No_Mapping> Customers_Consult_Person_Cell_No_Mapping { get; set; }
        public virtual DbSet<Customers_Consult_Person_Email_Mapping> Customers_Consult_Person_Email_Mapping { get; set; }
        public virtual DbSet<Customers_Consult_Person_Mapping> Customers_Consult_Person_Mapping { get; set; }
        public virtual DbSet<Customers_Consult_Person_Tel_No_Mapping> Customers_Consult_Person_Tel_No_Mapping { get; set; }
        public virtual DbSet<Customers_Service_Address_Cell_No_Mapping> Customers_Service_Address_Cell_No_Mapping { get; set; }
        public virtual DbSet<Customers_Service_Address_Email_Mapping> Customers_Service_Address_Email_Mapping { get; set; }
        public virtual DbSet<Customers_Service_Address_Mapping> Customers_Service_Address_Mapping { get; set; }
        public virtual DbSet<Customers_Service_Address_Tel_No_Mapping> Customers_Service_Address_Tel_No_Mapping { get; set; }
        public virtual DbSet<CustomerStatu> CustomerStatus { get; set; }
        public virtual DbSet<Department_Master> Department_Master { get; set; }
        public virtual DbSet<Documents_Templates> Documents_Templates { get; set; }
        public virtual DbSet<EmployeeDesignation> EmployeeDesignations { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employees_Status_Master> Employees_Status_Master { get; set; }
        public virtual DbSet<Estimate_Services_Mapping> Estimate_Services_Mapping { get; set; }
        public virtual DbSet<Estimate> Estimates { get; set; }
        public virtual DbSet<Estimates_History> Estimates_History { get; set; }
        public virtual DbSet<FrequencyOfInvoice> FrequencyOfInvoices { get; set; }
        public virtual DbSet<FrequencyOfService> FrequencyOfServices { get; set; }
        public virtual DbSet<Industry> Industries { get; set; }
        public virtual DbSet<Invoice_Customer_Service_Address_Mapping> Invoice_Customer_Service_Address_Mapping { get; set; }
        public virtual DbSet<Invoice_Services_Mapping> Invoice_Services_Mapping { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Lead_Cell_No_Mapping> Lead_Cell_No_Mapping { get; set; }
        public virtual DbSet<Lead_Consult_Person> Lead_Consult_Person { get; set; }
        public virtual DbSet<Lead_Consult_Person_Contact_No_Mapping> Lead_Consult_Person_Contact_No_Mapping { get; set; }
        public virtual DbSet<Lead_Consult_Person_Email_Mapping> Lead_Consult_Person_Email_Mapping { get; set; }
        public virtual DbSet<Lead_Email_Mapping> Lead_Email_Mapping { get; set; }
        public virtual DbSet<Lead_Locations_Mapping> Lead_Locations_Mapping { get; set; }
        public virtual DbSet<Lead_Services_Mapping> Lead_Services_Mapping { get; set; }
        public virtual DbSet<Lead_Services_Mapping_History> Lead_Services_Mapping_History { get; set; }
        public virtual DbSet<Lead_Tel_No_Mapping> Lead_Tel_No_Mapping { get; set; }
        public virtual DbSet<Lead> Leads { get; set; }
        public virtual DbSet<Leads_Follow_Up_Details> Leads_Follow_Up_Details { get; set; }
        public virtual DbSet<Leads_History> Leads_History { get; set; }
        public virtual DbSet<Leads_Import_Format> Leads_Import_Format { get; set; }
        public virtual DbSet<LeadStatus> LeadStatuses { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<PaymentMode> PaymentModes { get; set; }
        public virtual DbSet<PaymentTerm> PaymentTerms { get; set; }
        public virtual DbSet<Pending_Leads> Pending_Leads { get; set; }
        public virtual DbSet<Pending_Leads_Services> Pending_Leads_Services { get; set; }
        public virtual DbSet<PeriodsOfContract> PeriodsOfContracts { get; set; }
        public virtual DbSet<Premises_Area_Master> Premises_Area_Master { get; set; }
        public virtual DbSet<PremisesType> PremisesTypes { get; set; }
        public virtual DbSet<Product_Category_Master> Product_Category_Master { get; set; }
        public virtual DbSet<Products_Master> Products_Master { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<Service_Estimate_Templates> Service_Estimate_Templates { get; set; }
        public virtual DbSet<Service_Scope_Master> Service_Scope_Master { get; set; }
        public virtual DbSet<Service_Status_Master> Service_Status_Master { get; set; }
        public virtual DbSet<ServiceGroup> ServiceGroups { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Servicing_Chemicals_Issued> Servicing_Chemicals_Issued { get; set; }
        public virtual DbSet<Servicing_Technician_Mapping> Servicing_Technician_Mapping { get; set; }
        public virtual DbSet<Servicing> Servicings { get; set; }
        public virtual DbSet<Short_Service_Scope_Master> Short_Service_Scope_Master { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<UOM_Master> UOM_Master { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<UserLoginType> UserLoginTypes { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<Vendor_Cities> Vendor_Cities { get; set; }
        public virtual DbSet<Vendor_Locations> Vendor_Locations { get; set; }
        public virtual DbSet<Vendor_Services> Vendor_Services { get; set; }
    }
}
