//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicing_Chemicals_Issued
    {
        public int Servicing_Chemicals_Issued_ID { get; set; }
        public int ServicingID { get; set; }
        public int ChemicalID { get; set; }
        public Nullable<decimal> ChemicalQty { get; set; }
        public Nullable<byte> UOMID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> LastUpdatedByUserID { get; set; }
        public int TechnicianID { get; set; }
    
        public virtual Chemicals_Master Chemicals_Master { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        public virtual Servicing Servicing { get; set; }
        public virtual UOM_Master UOM_Master { get; set; }
    }
}
