//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicing()
        {
            this.Servicing_Chemicals_Issued = new HashSet<Servicing_Chemicals_Issued>();
            this.Servicing_Technician_Mapping = new HashSet<Servicing_Technician_Mapping>();
        }
    
        public int ServicingID { get; set; }
        public string ServicingNo { get; set; }
        public Nullable<int> TypeOfPremisesID { get; set; }
        public string PremisesArea { get; set; }
        public string PremisesAppSqFtArea { get; set; }
        public Nullable<System.DateTime> Period_Of_Contract_Start_Date { get; set; }
        public Nullable<System.DateTime> Period_Of_Contract_End_Date { get; set; }
        public Nullable<int> ServiceGroupID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> FrequencyOfServiceID { get; set; }
        public Nullable<byte> Servicing_Frequency_Number { get; set; }
        public string Quantity { get; set; }
        public Nullable<System.DateTime> System_Servicing_Datetime { get; set; }
        public Nullable<System.DateTime> Servicing_Datetime { get; set; }
        public Nullable<System.DateTime> Actual_Servicing_Datetime { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> PaymentModeID { get; set; }
        public Nullable<int> PaymentTermID { get; set; }
        public string PaidByCustomer { get; set; }
        public string BalanceAmount { get; set; }
        public string ServicingInstructions { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<int> Service_Status_ID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<int> LeadID { get; set; }
        public Nullable<int> Lead_Services_Mapping_ID { get; set; }
        public Nullable<int> NoOfServicing { get; set; }
        public Nullable<int> ContractID { get; set; }
        public Nullable<int> Contract_Services_Mapping_ID { get; set; }
        public Nullable<System.TimeSpan> Servicing_Time { get; set; }
        public Nullable<System.TimeSpan> Actual_Servicing_Time { get; set; }
        public string ComplaintContent { get; set; }
        public string ActualServiceID { get; set; }
    
        public virtual Contract_Services_Mapping Contract_Services_Mapping { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual FrequencyOfService FrequencyOfService { get; set; }
        public virtual Lead_Services_Mapping Lead_Services_Mapping { get; set; }
        public virtual Lead Lead { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual PaymentTerm PaymentTerm { get; set; }
        public virtual PremisesType PremisesType { get; set; }
        public virtual Service_Status_Master Service_Status_Master { get; set; }
        public virtual ServiceGroup ServiceGroup { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicing_Chemicals_Issued> Servicing_Chemicals_Issued { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicing_Technician_Mapping> Servicing_Technician_Mapping { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
