//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Scope_Master
    {
        public int Service_Scope_ID { get; set; }
        public int ServiceGroupID { get; set; }
        public int ServiceID { get; set; }
        public string Service_Scope { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int CreatedByUserID { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> LastUpdatedByUserID { get; set; }
        public byte Order { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
        public virtual Service Service { get; set; }
        public virtual ServiceGroup ServiceGroup { get; set; }
    }
}
