//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Contract_Services_Mapping = new HashSet<Contract_Services_Mapping>();
            this.Customer_Services_Mapping = new HashSet<Customer_Services_Mapping>();
            this.Estimate_Services_Mapping = new HashSet<Estimate_Services_Mapping>();
            this.Invoice_Services_Mapping = new HashSet<Invoice_Services_Mapping>();
            this.Lead_Services_Mapping = new HashSet<Lead_Services_Mapping>();
            this.Lead_Services_Mapping_History = new HashSet<Lead_Services_Mapping_History>();
            this.Service_Estimate_Templates = new HashSet<Service_Estimate_Templates>();
            this.Service_Scope_Master = new HashSet<Service_Scope_Master>();
            this.Servicings = new HashSet<Servicing>();
            this.Short_Service_Scope_Master = new HashSet<Short_Service_Scope_Master>();
            this.Vendor_Services = new HashSet<Vendor_Services>();
        }
    
        public int ServiceID { get; set; }
        public string ServiceName { get; set; }
        public string ServiceShortCode { get; set; }
        public Nullable<byte> GST { get; set; }
        public string SACCode { get; set; }
        public int ServiceGroupID { get; set; }
        public int ServiceSubGroupID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdateddate { get; set; }
        public Nullable<int> Order { get; set; }
        public string ShortServiceScope { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Services_Mapping> Contract_Services_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Services_Mapping> Customer_Services_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estimate_Services_Mapping> Estimate_Services_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Services_Mapping> Invoice_Services_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lead_Services_Mapping> Lead_Services_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lead_Services_Mapping_History> Lead_Services_Mapping_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_Estimate_Templates> Service_Estimate_Templates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_Scope_Master> Service_Scope_Master { get; set; }
        public virtual ServiceGroup ServiceGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicing> Servicings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Short_Service_Scope_Master> Short_Service_Scope_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor_Services> Vendor_Services { get; set; }
    }
}
