//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.Products_Master = new HashSet<Products_Master>();
            this.Servicings = new HashSet<Servicing>();
            this.Vendor_Cities = new HashSet<Vendor_Cities>();
            this.Vendor_Locations = new HashSet<Vendor_Locations>();
            this.Vendor_Services = new HashSet<Vendor_Services>();
        }
    
        public int VendorID { get; set; }
        public string VendorName { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> LastUpdatedByUserID { get; set; }
        public string VendorNo { get; set; }
        public Nullable<System.DateTime> VendorDate { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> StateID { get; set; }
        public string EmailID { get; set; }
        public string ContactPerson { get; set; }
        public string CellNo1 { get; set; }
        public string CellNo2 { get; set; }
        public string CellNo3 { get; set; }
        public string CellNo4 { get; set; }
        public string CellNo5 { get; set; }
        public string GSTNo { get; set; }
        public string AccountName1 { get; set; }
        public string AccountNo1 { get; set; }
        public string BankName1 { get; set; }
        public string IFSCCode1 { get; set; }
        public string AccountBranch1 { get; set; }
        public string AccountName2 { get; set; }
        public string AccountNo2 { get; set; }
        public string BankName2 { get; set; }
        public string IFSCCode2 { get; set; }
        public string AccountBranch2 { get; set; }
        public string AccountName3 { get; set; }
        public string AccountNo3 { get; set; }
        public string BankName3 { get; set; }
        public string IFSCCode3 { get; set; }
        public string AccountBranch3 { get; set; }
        public string AccountName4 { get; set; }
        public string AccountNo4 { get; set; }
        public string BankName4 { get; set; }
        public string IFSCCode4 { get; set; }
        public string AccountBranch4 { get; set; }
        public string AccountName5 { get; set; }
        public string AccountNo5 { get; set; }
        public string BankName5 { get; set; }
        public string IFSCCode5 { get; set; }
        public string AccountBranch5 { get; set; }
        public string SupplierType { get; set; }
        public string PaymentTerms { get; set; }
        public string Pincode { get; set; }
    
        public virtual City City { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_Master> Products_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicing> Servicings { get; set; }
        public virtual State State { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        public virtual UserLogin UserLogin2 { get; set; }
        public virtual UserLogin UserLogin3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor_Cities> Vendor_Cities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor_Locations> Vendor_Locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor_Services> Vendor_Services { get; set; }
    }
}
