//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadguruCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_Locations
    {
        public int Vendor_Location_ID { get; set; }
        public int VendorID { get; set; }
        public int LocationID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
